FROM node:7.1-slim

# Create app directory
RUN mkdir -p /myapp/src
RUN mkdir -p /myapp/www
RUN mkdir -p /myapp/resources
WORKDIR /myapp

# Install app dependencies
ADD config.xml /myapp/
ADD ionic.config.json /myapp/
ADD tsconfig.json /myapp/
ADD tslint.json /myapp/
ADD package.json /myapp/
RUN npm install

# Add app source
ADD src /myapp/src
ADD www /myapp/www
ADD resources /myapp/resources

EXPOSE 8080
CMD [ "npm", "start" ]
